"""Real PDF/PNG downloads plus hand-known report numbers; no customer fixtures."""
import functools,http.server,json,struct,tempfile,threading,re,os
import fitz
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'build/build.mjs').exists());passed=0
class Quiet(http.server.SimpleHTTPRequestHandler):
 def log_message(self,*a):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(ROOT/'dist')));threading.Thread(target=server.serve_forever,daemon=True).start()
def check(value,msg):
 global passed
 assert value,msg;passed+=1;print('PASS:',msg,flush=True)
def tab(p,n):p.evaluate(f'showTab({n})')
def openpage(b,phase):
 p=b.new_page(accept_downloads=True,viewport={'width':1400,'height':1000});p.console_errors=[];p.on('console',lambda message:p.console_errors.append(message.text) if message.type=='error' else None);p.errors=[];p.on('pageerror',lambda e:p.errors.append(str(e)));p.goto(f'http://127.0.0.1:{server.server_port}/{phase}.html');p.wait_for_function('() => typeof safeRender==="function"');check(not p.errors,phase+' loads without script errors');p.evaluate('''() => {document.querySelectorAll('.lang-picker-overlay,#tourOverlay').forEach(e=>e.remove());window.__reportRenderFailures=[];const old=window.safeRender;window.safeRender=function(label,fn){return old(label,()=>{try{return fn()}catch(e){window.__reportRenderFailures.push(String(label)+':'+e.message);throw e}})};safeRender('report-canary',()=>{throw Error('canary')});}''');check(p.evaluate("window.__reportRenderFailures.some(v=>v.includes('canary'))"),phase+' swallowed-render detector canary');p.evaluate('window.__reportRenderFailures=[]');return p
def dl(p,sel,path):
 try:
  with p.expect_download(timeout=90000) as d:p.locator(sel).click()
 except Exception:
  print('DOWNLOAD FAILURE:', p.console_errors, p.locator('body').inner_text()[-3000:], flush=True)
  raise
 d.value.save_as(str(path));return path.read_bytes()
def pdf_layout(data,module):
 with fitz.open(stream=data,filetype='pdf') as doc:
  outside=[];stale=[];numbering=[]
  complete_text='\n'.join(page.get_text() for page in doc)
  check(not re.search(r'asy\.workflow\.pdf\.|reportSummary\.brief\.|"covarianceMode"',complete_text),module+' detail pages print readable audit fields without raw JSON or translation keys')
  cover=doc[0];cover_text=cover.get_text();cover_spans=[span for block in cover.get_text('dict')['blocks'] if block['type']==0 for line in block['lines'] for span in line['spans']]
  large_metrics=[span for span in cover_spans if span['size']>=14 and 69*72/25.4<span['bbox'][1]<143*72/25.4]
  check(len(large_metrics)==4,module+' first page shows exactly four prominent metric cards')
  check(len(cover_text.split())<=220 and not re.search(r'\{\w+\}|covarianceMode|reportSummary\.',cover_text),module+' executive page stays concise without raw keys or unresolved fields')
  check(('WHAT TO CHECK' in cover_text and 'RECOMMENDED NEXT STEP' in cover_text) or ('YANG PERLU DIPERIKSA' in cover_text and 'LANGKAH BERIKUTNYA' in cover_text),module+' cover gives a clear inspection priority and next action')
  check(len(doc)>1 and ('Results and interpretation' in doc[1].get_text() or 'Hasil dan interpretasi' in doc[1].get_text()),module+' full interpretation follows the executive page immediately')
  check(doc.metadata.get('title','').startswith('Orebit '),module+' PDF carries a readable document title')
  toc=doc.get_toc();check(len(toc)>=2 and toc[0][2]==1 and all(1<=row[2]<=len(doc) for row in toc),module+' PDF bookmarks reach the final summary and audit pages after insertion')
  for i,page in enumerate(doc,1):
   blocks=page.get_text('blocks');footer='\n'.join(b[4] for b in blocks if b[1]>page.rect.height-45)
   numbering.append(re.search(r'(?m)^'+re.escape(f'{i} / {len(doc)}')+r'$' ,footer) is not None)
   if re.search(r'\bPage\s+\d+\s+of\s+\d+\b',footer):stale.append(i)
   outside.extend((i,b[4][:80]) for b in blocks if b[0]<-.5 or b[1]<-.5 or b[2]>page.rect.width+.5 or b[3]>page.rect.height+.5)
  check(not outside,module+' PDF text remains inside every page: '+repr(outside))
  check(not stale and all(numbering),module+' PDF has final numbering on every page with no legacy totals: '+repr(stale))
def pdf(p,sel,path,module):
 data=dl(p,sel,path);p.wait_for_timeout(200);
 if p.locator('#orebit-support-moment .support-close-btn').is_visible():p.locator('#orebit-support-moment .support-close-btn').click()
 check(data.startswith(b'%PDF-') and b'%%EOF' in data and b'Screening due-diligence insight' in data,module+' PDF downloads with audit appendix');check(b'Results and next steps' in data,module+' PDF opens with a readable executive summary')
 pdf_layout(data,module)
 brief=p.evaluate('() => window._reportBriefSnapshot')
 with fitz.open(stream=data,filetype='pdf') as doc:
  cover=doc[0].get_text()
  check(brief['detailStartPage']==2 and len(brief['metrics'])==4 and all(metric['label'] in cover for metric in brief['metrics']),module+' native PDF uses the exact current executive model')
  check(all(metric['value'] is None or str(metric['value']).replace('³','3').replace('²','2') in cover for metric in brief['metrics']),module+' all four current values reach the native PDF without rounding them into another result')
  if os.environ.get('OREBIT_REPORT_PROOF_DIR') and path.name in ('core.pdf','assay.pdf','resource-cutoff.pdf'):
   proof=Path(os.environ['OREBIT_REPORT_PROOF_DIR']);proof.mkdir(parents=True,exist_ok=True);(proof/path.name).write_bytes(data);doc[0].get_pixmap(matrix=fitz.Matrix(1.5,1.5)).save(str(proof/(path.stem+'-cover.png')))
 return dict(p.evaluate('() => window._reportAuditSnapshot.rows'))
try:
 with tempfile.TemporaryDirectory() as t,sync_playwright() as pw:
  tmp=Path(t);b=pw.chromium.launch(headless=True,args=['--no-sandbox'])
  collar=tmp/'collar.csv';collar.write_text('hole_id,x,y,z,depth\nH1,100,200,300,4\nH2,130,200,300,4\nH3,160,200,300,4\n')
  survey=tmp/'survey.csv';survey.write_text('hole_id,depth,dip,azimuth\nH1,0,-90,0\nH1,4,-90,0\nH2,0,-90,0\nH2,4,-90,0\nH3,0,-90,0\nH3,4,-90,0\n')
  assay=tmp/'assay.csv';assay.write_text('hole_id,from_m,to_m,au_gpt,x,y,z\nH1,0,2,0,100,200,299\nH1,2,4,2,100,200,297\nH2,0,2,4,130,200,299\nH2,2,4,6,130,200,297\nH3,0,2,8,160,200,299\nH3,2,4,10,160,200,297\n')
  c=openpage(b,'Core');tab(c,2);c.locator('#fileInput').set_input_files([str(collar),str(survey),str(assay)]);c.wait_for_function('() => STATE.assay.length===6&&!STATE.isSample.assay');c.evaluate('STATE.survey=[]');check(c.evaluate("_p1RunValidationChecks().some(r=>r.name==='Linkage and geometry verdict'&&r.value==='FIX REQUIRED')"),'Core PDF never calls missing geometry ready');tab(c,2);c.locator('#coreProvidedXYZ').check();c.evaluate('computeMerge()');tab(c,13);dl(c,'button[onclick="exportMasterCSV()"]',tmp/'master.csv');cr=pdf(c,'#pdf-export-btn',tmp/'core.pdf','Core');check('Supplied' in cr['Coordinate source'] and 'READY' in cr['Geometry readiness'],'Core report states explicit supplied geometry and readiness');check('including valid zero' in cr['Grade statistics population'],'Core PDF grade population includes valid zeros')
  a=openpage(b,'Assay');tab(a,2);a.locator('#fileInput').set_input_files(str(tmp/'master.csv'));a.wait_for_function('() => DATA.rows.length===6&&currentTab===3');tab(a,7);a.locator('#compLength').fill('2');a.locator('#compLength').press('Tab');tab(a,13);dl(a,'#tab13 button.secondary[onclick="exportMasterForEstimation()"]',tmp/'composites.csv');tab(a,13);ar=pdf(a,'#btnReportPdf',tmp/'assay.pdf','Assay');check('6 / 5.000 / 5.000' in a.locator('#tab13').inner_text(),'Assay report UI and PDF statistics use the same population including zero');check('No method justification provided' in ar['Method justification'],'Assay report records missing method rationale explicitly');check(ar['Composite settings'].startswith('2m;'),'Assay PDF uses actual composite length');check('Input 60.000000; composite 60.000000;' in ar['Grade x informed length'],'Assay report proves exact informed-length grade conservation');check('n=6' in ar['Grade statistics population'],'Assay valid zero belongs to reported population');check('not applied' in ar['Hypothetical sensitivity'].lower() and 'none' in ar['Actual treatment record'].lower(),'Hypothetical P99 is separate from actual treatment provenance')
  tab(a,8);png=dl(a,'#statHistExportPngBtn',tmp/'assay.png');check(png.startswith(b'\x89PNG\r\n\x1a\n') and struct.unpack('>II',png[16:24])==(2800,1800),'Assay native PNG export is an actual fixed-size chart')
  tab(a,11);a.locator('#domainElementSelect').select_option('au_gpt');a.locator('#domainMethodSelect').select_option('cutoff');a.locator('#domainCutoff').fill('0');a.locator('#domainCutoff').press('Tab');check(a.evaluate("window._domainAudit.cutoff===0&&window._domainTagged.every(r=>r.domain==='M1-Mineralised')"),'Assay zero cutoff is recorded exactly and keeps valid zero grades');tab(a,13);a.locator('#assayReportNote').fill('Grade grouping for screening; not an economic cutoff.');domain_report=pdf(a,'#btnReportPdf',tmp/'domain-zero.pdf','Assay optional cutoff');check(domain_report['Method justification']=='Grade grouping for screening; not an economic cutoff.','Assay PDF records the supplied method rationale separately from controls');check('cutoff >= 0 g/t' in domain_report['Domain definition'],'Assay PDF records actual domain method, element and zero cutoff: '+repr(domain_report['Domain definition']));tab(a,11);a.locator('#domainMethodSelect').select_option('lithology');tab(a,13);no_cut_report=pdf(a,'#btnReportPdf',tmp/'domain-existing.pdf','Assay source domains');check('lithology' in no_cut_report['Domain definition'] and 'no grade cutoff recorded' in no_cut_report['Domain definition'],'Assay lithology-domain mode reports no grade cutoff');tab(a,9);a.locator('#tcElementSelect').select_option('au_gpt');a.locator('#customCut').fill('5');a.locator("button[onclick=\"applyTopCut('au_gpt')\"]").click();tab(a,13);capped_report=pdf(a,'#btnReportPdf',tmp/'actual-cap.pdf','Assay actual cap');check('5' in capped_report['Actual treatment record'] and 'Input 42.000000; composite 42.000000;' in capped_report['Grade x informed length'],'Assay PDF reports a real applied cap and conserved capped grade-length, distinct from P99')
  missing=tmp/'missing-grade.csv';missing.write_text('hole_id,from_m,to_m,au_gpt,midx,midy,midz\nH1,0,2,,100,200,299\nH2,0,2,,130,200,299\n');tab(a,2);a.locator('#fileInput').set_input_files(str(missing));a.wait_for_function('() => DATA.rows.length===2&&currentTab===3');check(a.locator('#assayReportNote').input_value()=='','New Assay dataset clears the previous analyst rationale');a.evaluate("window._gradeColOverride='au_gpt';window._primaryElement='au_gpt'");tab(a,13);missing_report=pdf(a,'#btnReportPdf',tmp/'missing-assay.pdf','Assay missing grades');check('n=0' in missing_report['Grade statistics population'] and 'No valid grades' in missing_report['Result'],'All-missing assays produce an explicit no-result report rather than invented zero statistics')
  mixed=tmp/'mixed-master.csv';mixed.write_text('hole_id,from_m,to_m,au_gpt,ag_gpt,midx,midy,midz,domain\nH1,0,2,4,,100,200,299,D\nH1,2,4,,1,100,200,297,D\nH2,0,2,0,0,130,200,299,D\nH2,2,4,0,0,130,200,297,D\nH3,0,2,0,0,160,200,299,D\nH3,2,4,0,0,160,200,297,D\n');tab(a,2);a.locator('#fileInput').set_input_files(str(mixed));a.wait_for_function('() => DATA.rows.length===6&&currentTab===3');tab(a,8);a.locator('#statsElementSelect').select_option('au_gpt');tab(a,7);a.locator('#compLength').fill('4');a.locator('#compLength').press('Tab');tab(a,13);mixed_report=pdf(a,'#btnReportPdf',tmp/'mixed.pdf','Assay mixed support');check('Input 8.000000; composite 8.000000;' in mixed_report['Grade x informed length'],'Missing Au with present Ag uses Au-specific informed support')
  r=openpage(b,'Resource');tab(r,2);r.locator('#fileInput').set_input_files(str(tmp/'composites.csv'));r.wait_for_function('() => DATA.rows.length===6');r.evaluate('''() => {setupState.element='au_gpt';setupState.domain='all';variogramState.model={type:'spherical',nugget:.1,sill:1,range:40,covarianceMode:'model-range',unit:'m'};variogramState.experimental={lags:[5,10,20],gammas:[.2,.4,.7],pairs:[10,10,10]};blockState.size=[1,1,1];blockState.origin=[100,200,297];blockState.dims=[2,1,1];blockState.blocks=[{cx:100.5,cy:200.5,cz:297.5,idx:0},{cx:101.5,cy:200.5,cz:297.5,idx:1}];blockState.blockDensities=new Float32Array([1,3]);estimState={done:true,results:{ok:new Float32Array([1,3]),idw:new Float32Array([1,3]),nn:new Float32Array([1,3]),variance:new Float32Array([.1,.1]),nearestDist:new Float32Array([2,2]),nNb:new Int16Array([6,6]),passNumber:new Uint8Array([1,2]),nHoles:new Int16Array([2,2]),estimated:2}};classState.labels=new Uint8Array([3,3]);classState.thresholds={measVar:.5,indVar:.8,measDist:20,indDist:40,measNeigh:6,indNeigh:4};}''')
  tab(r,10);r.locator('#gtMin').fill('1');r.locator('#gtMax').fill('4');r.locator('#gtSteps').fill('7');r.locator('#gtClass').uncheck();r.locator('button[onclick="computeGT()"]').click();before=r.evaluate('() => window._gtCurveSnapshot');check(abs(before['meanG'][0]-2.5)<1e-10 and abs(before['tons'][0]-4e-6)<1e-12,'GT density-weighted mean and tonnes agree with hand answer (10g Au)');tab(r,12);rr=pdf(r,'#pdf-export-btn',tmp/'resource.pdf','Resource');after=r.evaluate('() => window._gtCurveSnapshot');check(before==after,'Resource PDF preserves cutoff range, steps, class filter and exact curve');check('independent of search' in rr['Calculation'] and 'model-range' in rr['Complete covariance model'],'Resource PDF declares effective physical covariance');check(json.loads(rr['Search pass counts'])=={'1':1,'2':1},'Resource PDF records primary and fallback counts');check('not a geological solid' in rr['Geometry limitation'] or 'geological limits' in rr['Geometry limitation'],'Report distinguishes screening envelope from verified geology')
  r.locator('#reportCutoff').fill('1.5');r.locator('#reportCutoffNote').fill('Independent comparison threshold; no economic assumptions.');cutoff_report=pdf(r,'#pdf-export-btn',tmp/'resource-cutoff.pdf','Resource exact cutoff');headline=r.evaluate('() => window._resourceReportSnapshot');check(headline['cutoff']==1.5 and headline['generated']['mt']==4e-6 and headline['estimated']['mt']==4e-6 and headline['selected']['mt']==3e-6 and headline['selected']['meanGrade']==3 and abs(headline['metalTonnes']-9e-6)<1e-15,'Exact PDF cutoff between curve points reconciles generated, estimated and selected tonnage to hand answer');check('Cutoff >= 1.5 g/t' in cutoff_report['Headline result'] and '3 blocks' not in cutoff_report['Headline result'],'Readable PDF headline declares cutoff and actual block count');check(before==r.evaluate('() => window._gtCurveSnapshot'),'Headline cutoff leaves original curve controls and results unchanged');check(cutoff_report['Cutoff justification']=='Independent comparison threshold; no economic assumptions.','User cutoff rationale is carried into the PDF without inventing economics')
  check(r.evaluate("window._reportBriefSnapshot.metrics.map(m=>m.value)")==['3 t','3 g/t','0.000009 t','100 %'],'Resource executive card values reconcile to independent hand answers at the user cutoff')
  r.locator('#reportCutoff').fill('0.0000001');tiny_report=pdf(r,'#pdf-export-btn',tmp/'tiny-cutoff.pdf','Resource tiny cutoff');check('1e-7' in tiny_report['Report cutoff and confidence scope'] and r.evaluate('window._resourceReportSnapshot.cutoff')==1e-7,'Tiny report cutoff is recorded exactly without rounding to zero')
  r.locator('#reportCutoffNote').fill('');r.locator('#reportCutoff').fill('4');pdf(r,'#pdf-export-btn',tmp/'resource-empty.pdf','Resource empty selection');empty=r.evaluate('() => window._resourceReportSnapshot');check(empty['selected']['blocks']==0 and empty['selected']['meanGrade'] is None and empty['metalTonnes'] is None,'No blocks above report cutoff produces no invented grade or metal');check('No justification provided' in r.evaluate('window._resourceReportSnapshot.justification'),'Missing justification is explicitly recorded');r.locator('#reportCutoff').fill('1.5');r.evaluate("setReportCutoff('1.5');saveResourceSession();setupState.reportCutoff=null;restoreResourceSession()");check(r.evaluate('setupState.reportCutoff===1.5'),'Report cutoff persists for the matching dataset');
  tab(r,10);r.evaluate('classState.labels[0]=1');r.locator('#gtClass').check();r.locator('button[onclick="computeGT()"]').click();tab(r,12);r.locator('#reportCutoff').fill('');filtered=pdf(r,'#pdf-export-btn',tmp/'confidence-only.pdf','Resource confidence filter');filtered_state=r.evaluate('window._resourceReportSnapshot');check(filtered_state['cutoff'] is None and filtered_state['useClass'] and filtered_state['selected']['mt']==3e-6 and 'High + medium confidence only' in filtered['Headline result'],'PDF records the current confidence filter with an explicit no-cutoff selection');r.evaluate("applyLanguage('id')");indonesian=dl(r,'#pdf-export-btn',tmp/'resource-id.pdf');check(b'Ringkasan hasil dan langkah berikutnya' in indonesian and r.evaluate('window._resourceReportSnapshot.selected.mt')==3e-6,'Indonesian readable summary retains the same selected tonnes');pdf_layout(indonesian,'Resource Indonesian');r.evaluate("applyLanguage('en')");
  tab(r,10);png=dl(r,'#gtPlotExportPngBtn',tmp/'resource.png');check(png.startswith(b'\x89PNG\r\n\x1a\n'),'Resource native PNG download works')
  r.evaluate("_recordExport('PNG','oversize-canary',{filename:'large.png',mime:'image/png',content:'data:image/png;base64,'+'A'.repeat(2000001)})");check(r.evaluate("JSON.parse(localStorage.getItem('orebitExportHistory'))[0].content===''"),'Oversized PNG is never stored as a corrupt partial download')
  # A real Assay unit assignment must survive its native master export and Resource import.
  unitpage=openpage(b,'Resource')
  for unit,expected in [('g/t',.00001),('ppm',.00001),('%',.1),('kg/m³',.004)]:
   tab(a,2);a.evaluate('renderColumnMapping(DATA.detectedMap||{})')
   a.locator('#p2GradeCol').select_option('au_gpt');a.locator('#p2GradeUnit').select_option(unit);a.locator('#p2ApplyMapping').click()
   with a.expect_download(timeout=60000) as download:a.evaluate('exportMasterForEstimation()')
   master=tmp/('unit-'+str(unit).replace('/','-')+'.csv');download.value.save_as(str(master))
   tab(unitpage,2);unitpage.locator('#fileInput').set_input_files(str(master));unitpage.wait_for_function('(unit)=>setupState.gradeUnit===unit',arg=unit)
   check(unitpage.evaluate('gradeUnitFor(setupState.element)')==unit,'Actual Assay assigned '+unit+' survives native CSV export and Resource import')
   unitpage.evaluate("""() => {blockState.size=[1,1,1];blockState.blocks=[{cx:0,cy:0,cz:0},{cx:1,cy:0,cz:0}];blockState.dims=[2,1,1];blockState.origin=[0,0,0];blockState.density=isVolumetricGrade(setupState.element)?1:3;blockState.blockDensities=isVolumetricGrade(setupState.element)?null:new Float64Array([1,3]);blockState.densityAssigned=new Uint8Array([1,0]);blockState.densitySource='sample';variogramState.model={type:'spherical',nugget:.1,sill:1,range:40,covarianceMode:'model-range'};variogramState.experimental={lags:[5,10],gammas:[.2,.4],pairs:[5,5]};estimState={done:true,results:{ok:[1,3],idw:[1,3],nn:[1,3],variance:[.1,.1],nNb:[6,6],nearestDist:[1,1],passNumber:[1,1],estimated:2}};classState.labels=null;}""")
   actual=unitpage.evaluate('resourceReportSummary(null,false)')
   check(abs(actual['metalTonnes']-expected)<1e-14,'Independent two-cell metal conversion is correct for '+unit+' including density/volume weighting')
   if unit=='kg/m³':
    tab(unitpage,10);unitpage.locator('#gtClass').uncheck();unitpage.locator('button[onclick="computeGT()"]').click()
    check(unitpage.evaluate("gtPlot.layout.yaxis.title.text==='Volume (Mm³)'"),'Volumetric cutoff curve is labelled as volume, not nominal rock mass')
    tab(unitpage,12);vol_report=pdf(unitpage,'#pdf-export-btn',tmp/'resource-volumetric.pdf','Resource volumetric')
    check(unitpage.evaluate('window._reportBriefSnapshot.metrics[0].value')=='2 m³','Volumetric PDF executive card reports actual selected volume rather than fake tonnes')
    check('Rock tonnage is not determined' in vol_report['Headline result'],'Volumetric PDF explicitly distinguishes volume and contained metal from rock tonnage')
    check('not determined' in vol_report['Effective unit conversion'],'PDF records the actual volumetric formula')
  unitpage.close();tab(a,13)
  tab(r,12);r.evaluate('estimState.done=false');pdf(r,'#pdf-export-btn',tmp/'not-estimated.pdf','Resource not estimated')
  check(r.evaluate('window._reportBriefSnapshot.metrics.every(m=>m.value===null)'),"Unrun Resource estimate shows unavailable metrics, never invented zero tonnes/grade/metal/coverage")
  for pg,name,selector in [(c,'Core','#pdf-export-btn'),(a,'Assay','#btnReportPdf')]:
   pg.evaluate("applyLanguage('id')");pdf_layout(dl(pg,selector,tmp/(name+'-id.pdf')),name+' Indonesian');pg.evaluate("applyLanguage('en')")
  for pg,name in [(c,'Core'),(a,'Assay'),(r,'Resource')]:
   check(not pg.errors and pg.evaluate('window.__reportRenderFailures.length===0'),name+' reports produce no page or swallowed renderer failures: '+str(pg.errors)+' / '+str(pg.evaluate('window.__reportRenderFailures')))
  check(r.evaluate("(() => {const old=setupState.reportCutoff;setActiveDataset(DATA,{source:'upload'});const ok=setupState.reportCutoff===null&&document.getElementById('reportCutoff').value==='';setupState.reportCutoff=old;return ok})()"),'Every dataset entry resets the previous report cutoff')
  b.close()
finally:server.shutdown();server.server_close()
print('SCREENING REPORTS:',passed,'passed',flush=True)
