"""Real navigation, source correction and block topology; no synthetic UI approval."""
import functools, http.server, json, os, tempfile, threading
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'build/build.mjs').exists())
DIST=Path(os.environ.get('OREBIT_TEST_DIST',ROOT/'dist'))
class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(DIST)))
threading.Thread(target=server.serve_forever,daemon=True).start()
passed=0
def check(ok,message):
    global passed
    assert ok,message
    passed+=1
    print('PASS:',message,flush=True)
def open_page(browser,name):
    p=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True)
    p.goto(f'http://127.0.0.1:{server.server_port}/{name}.html')
    p.wait_for_function('() => window.__i18nBooted===true')
    p.evaluate("document.querySelectorAll('.lang-picker-overlay,#tourOverlay').forEach(e=>e.remove());applyLanguage('en');window.orebitConfirm=async()=>true")
    p.evaluate("""() => {window.renderFailures=[];const original=window.safeRender;if(original)window.safeRender=function(name,fn){return original(name,()=>{try{return fn()}catch(e){renderFailures.push(String(e));throw e}})}}""")
    if p.evaluate("typeof safeRender==='function'"):
        p.evaluate("safeRender('canary',()=>{throw new Error('context-canary')})")
        check(p.evaluate("renderFailures.some(s=>s.includes('context-canary'))"),name+' detector catches swallowed render failures')
        p.evaluate('renderFailures=[]')
    return p
try:
    with sync_playwright() as pw,tempfile.TemporaryDirectory() as tmp:
        b=pw.chromium.launch()
        c=open_page(b,'Core')
        errors=[];c.on('pageerror',lambda e:errors.append(str(e)))
        source=c.evaluate('JSON.stringify(SAMPLE_DATA)');tables=json.loads(source)
        paths=[]
        for name,rows in tables.items():
            if name not in ('collar','survey','assay','geology'):continue
            csv=c.evaluate('(rows)=>trainingExerciseCSV(rows)',rows)
            path=Path(tmp)/(name+'.csv');path.write_text(csv);paths.append(str(path))
        c.evaluate('showTab(2)');c.locator('#fileInput').set_input_files(paths)
        c.wait_for_function('() => STATE.assay.length===8896')
        c.evaluate('showTab(7)')
        checks=c.evaluate('_p1RunValidationChecks()')
        check(not any(x['severity']=='fail' for x in checks),'Four uploaded original CSVs pass actual validation')
        before=c.evaluate('JSON.stringify([STATE.collar,STATE.assay,STATE.geology])')
        for stage in (3,4,5,6):
            c.locator(f'#tab7 [data-related-stage="{stage}"]').click()
            check(c.locator(f'#tab{stage}').evaluate('e=>e.classList.contains("active")'),'Validation opens source table '+str(stage)+' directly')
            check(c.locator('#orebitCrumb').inner_text()==c.locator('nav.tabs .tab').nth(stage-1).inner_text().strip(),'Core header follows directly opened source table '+str(stage))
            c.locator(f'#tab{stage} .workflow-related').get_by_role('button',name='← Back to Validation',exact=True).click()
        check(before==c.evaluate('JSON.stringify([STATE.collar,STATE.assay,STATE.geology])'),'Source inspections preserve measured data')
        c.locator('#tab7 [data-workflow-next]').click()
        c.wait_for_function('() => STATE.desurvey?.holes && Object.keys(STATE.desurvey.holes).length===350')
        check(c.locator('#tab10 [data-workflow-next]').is_enabled(),'Computed Desurvey unlocks Merge using the actual trace owner')
        c.locator('#tab10 [data-workflow-next]').click()
        check(c.locator('#mergePanel').is_visible() and c.evaluate('STATE.merged.length===8896'),'Next really opens and computes the merged table')
        c.evaluate("showTab(7);STATE.usingSample=true;OrebitScreeningWorkflow.refresh(7)")
        check(c.locator('#tab7 .workflow-training').is_visible(),'Imperfect exercise is discoverable from Validation itself')
        c.locator('#tab7 .workflow-training button').click()
        c.wait_for_function('() => window.__coreTrainingActive && STATE.collar.length===349')
        check(sum(x['severity']=='fail' for x in c.evaluate('_p1RunValidationChecks()'))>=4,'Teaching action really produces missing-link failures')
        check(c.locator('#tab7 [data-workflow-next]').is_disabled(),'Broken exercise cannot advance to geometry')
        check(c.locator('#tab7 .workflow-gate').is_visible(),'Blocked action explains what must be corrected')
        c.locator('#tab7 .workflow-training button').click()
        c.wait_for_function('() => !window.__coreTrainingActive && STATE.collar.length===350')
        check(not any(x['severity']=='fail' for x in c.evaluate('_p1RunValidationChecks()')),'Restore original synthetic CSVs clears real failures through normal import')
        check(c.evaluate('STATE.desurvey===null && STATE.merged===null'),'Correction invalidates previous derived geometry and merge')
        check(source==c.evaluate('JSON.stringify(SAMPLE_DATA)'),'Exercise and correction never mutate the immutable reference')
        c.evaluate('showTab(10)');c.evaluate('STATE.desurvey=null;OrebitScreeningWorkflow.refresh(10)')
        check(c.locator('#tab10 [data-workflow-next]').is_disabled(),'Absent traces still prevent false advancement')
        check(not errors and c.evaluate('renderFailures.length===0'),'Core has no page or swallowed renderer errors')
        c.close();c=open_page(b,'Core')
        supplied=Path(tmp)/'supplied';supplied.mkdir()
        (supplied/'collar.csv').write_text('hole_id,x,y,z,depth\nH1,100,200,300,2\n')
        (supplied/'assay.csv').write_text('hole_id,from_m,to_m,au_gpt,midx,midy,midz\nH1,0,2,1,110,210,299\n')
        c.evaluate('showTab(2)');c.locator('#fileInput').set_input_files([str(supplied/'collar.csv'),str(supplied/'assay.csv')]);c.wait_for_function('() => STATE.assay.length===1 && !STATE.survey.length')
        c.locator('#coreProvidedXYZ').check();c.evaluate('showTab(7)')
        c.locator('#tab7 [data-workflow-next]').click()
        check(c.locator('#tab11').evaluate('e=>e.classList.contains("active")'),'Explicit supplied coordinates bypass an inapplicable Desurvey stage')
        check(c.evaluate('STATE.merged[0].midx===110 && STATE.merged[0].midy===210 && STATE.merged[0].midz===299'),'Supplied coordinate workflow preserves actual interval geometry')
        check(c.locator('#tab11 [data-workflow-next]').is_enabled(),'A completed supplied-coordinate merge can continue to Export without invented surveys')
        c.close()
        a=open_page(b,'Assay')
        fixture=Path(tmp)/'related-gold.csv';fixture.write_text('hole_id,from_m,to_m,au_gpt,cu_pct,midx,midy,midz,domain\n'+''.join(f'H{i//4},{i%4*2},{i%4*2+2},{i},{i/10},{100+i//4*30},200,{300-i%4*2},D\n' for i in range(12)))
        a.evaluate('showTab(2)');a.locator('#fileInput').set_input_files(str(fixture));a.wait_for_function('() => DATA.rows.length===12')
        snapshot=a.evaluate('JSON.stringify(DATA.rows)')
        inventory={3:[12,6],8:[9,4,5],11:[10,5],7:[6,12]}
        for origin,targets in inventory.items():
            for target in targets:
                a.evaluate('(n)=>showTab(n)',origin)
                a.locator(f'#tab{origin} [data-related-stage="{target}"]').click()
                check(a.locator(f'#tab{target}').evaluate('e=>e.classList.contains("active")'),'Assay related tool '+str(target)+' opens directly from '+str(origin))
                check(a.locator('#orebitCrumb').inner_text()==a.locator('nav.tabs .tab').nth(target-1).inner_text().strip(),'Assay header follows directly opened related tool '+str(target))
                a.locator(f'#tab{target} .workflow-related').get_by_role('button',name='← Back to '+a.locator(f'nav.tabs .tab').nth(origin-1).inner_text().strip(),exact=True).click()
        check(snapshot==a.evaluate('JSON.stringify(DATA.rows)'),'Optional Assay navigation preserves selected raw population')
        check(a.evaluate('renderFailures.length===0'),'Assay related inspections have no swallowed render failures')
        a.close()
        # Uploaded screening workflow: only primary Next actions perform the
        # necessary calculations. No injected grid, model or estimator result.
        r=open_page(b,'Resource')
        automatic=Path(tmp)/'automatic-gold.csv'
        automatic.write_text('hole_id,from_m,to_m,au_gpt,midx,midy,midz,domain,density\n'+''.join(
            f'H{i//5},{i%5},{i%5+1},{1+(i%7)*0.3},{(i//5%4)*40},{(i//20)*40},{300-i%5*5},D,2.7\n' for i in range(40)))
        r.evaluate('showTab(2)');r.locator('#fileInput').set_input_files(str(automatic))
        r.wait_for_function('() => DATA.rows.length===40 && DATA.source==="upload"')
        r.evaluate('showTab(3)');r.locator('#resourceSetupNext').click()
        check(r.locator('#tab4 [data-workflow-next]').is_enabled(),'Uploaded data can compute continuity from the primary Next action')
        r.locator('#tab4 [data-workflow-next]').click()
        r.wait_for_function('() => document.getElementById("tab5").classList.contains("active")')
        check(r.evaluate('!!variogramState.model && !!variogramState.experimental'),'Primary Next computes a real fitted variogram before opening grid setup')
        # A manually applied model must survive Next, not be auto-fitted again.
        r.evaluate('showTab(4)');r.locator('#variogramModelCustom>summary').click()
        r.locator('#varRange').fill('777');r.locator('button[onclick="updateModel()"]').click()
        r.locator('#tab4 [data-workflow-next]').click()
        check(r.evaluate('variogramState.model.range===777'),'Guided continuation retains an applied custom model')
        for name,value in (('bmX','30'),('bmY','30'),('bmZ','10'),('bmDens','0')):
            r.locator('#'+name).fill(value)
        r.locator('#tab5 [data-workflow-next]').click()
        r.wait_for_function('() => document.querySelector("#tab5 .workflow-gate").textContent.includes("not completed")')
        check(r.locator('#tab5').evaluate('e=>e.classList.contains("active")') and r.evaluate('!blockState.blocks'),'Invalid density prevents an automatic grid and false advancement')
        r.evaluate('OrebitScreeningWorkflow.refresh(5)')
        check(r.locator('#tab5 .workflow-gate').is_visible() and r.evaluate("document.querySelector('#tab5 .workflow-gate').textContent===window.__t('flow.notAdvanced')"),'A panel refresh retains the real failed-calculation explanation')
        for language in ('id','en'):
            r.evaluate('(language)=>applyLanguage(language)',language)
            check(r.evaluate("[bmX.value,bmY.value,bmZ.value,bmDens.value].join(',')==='30,30,10,0'"),'Language switch preserves custom grid dimensions and the invalid density draft in '+language)
            r.locator('#bmDens').fill('0');r.locator('#tab5 [data-workflow-next]').click()
            r.wait_for_function("()=>document.querySelector('#tab5 .workflow-gate').textContent===window.__t('flow.notAdvanced')")
            r.evaluate('OrebitScreeningWorkflow.refresh(5)')
            check(r.locator('#tab5 .workflow-gate').is_visible(),'Failed grid explanation survives refresh in '+language)
        r.evaluate('OrebitScreeningWorkflow.reset();OrebitScreeningWorkflow.refresh(5)')
        check(r.locator('#tab5 .workflow-gate').is_hidden(),'Dataset-reset owner clears the previous failed attempt')
        r.locator('#tab5 [data-workflow-next]').click()
        r.wait_for_function("()=>document.querySelector('#tab5 .workflow-gate').textContent===window.__t('flow.notAdvanced')")
        r.locator('#bmDens').fill('2.7')
        check(r.locator('#tab5 .workflow-gate').is_hidden(),'Editing the invalid parameter clears the old error before a genuine retry')
        r.locator('#bmDens').fill('2.7');r.locator('#tab5 [data-workflow-next]').click()
        r.wait_for_function('() => document.getElementById("tab6").classList.contains("active")')
        check(r.evaluate('blockState.blocks.length>0 && blockState.size.join(",")==="30,30,10"'),'Primary Next creates actual cells using editable custom dimensions')
        r.locator('#srMin').fill('0');r.locator('#tab6 [data-workflow-next]').click()
        r.wait_for_function('() => document.querySelector("#tab6 .workflow-gate").textContent.includes("not completed")')
        check(r.locator('#tab6').evaluate('e=>e.classList.contains("active")') and r.evaluate('!estimState.done'),'Invalid search parameters stop automatic estimation before the next stage')
        r.locator('#srMin').fill('50');r.locator('#tab6 [data-workflow-next]').click()
        r.wait_for_function('() => document.getElementById("tab7").classList.contains("active")',timeout=120000)
        check(r.evaluate('estimState.done && estimState.results.estimated>0'),'Primary Next runs the genuine estimator and exposes cross-validation')
        r.locator('#tab7 [data-workflow-next]').click()
        r.wait_for_function('() => document.getElementById("tab10").classList.contains("active")',timeout=120000)
        check(r.evaluate('!!crossvalState.metrics && !crossvalState._running'),'Cross-validation finishes before automatic continuation')
        applied=r.evaluate('estimState.appliedSignature')
        check(applied==r.evaluate('resourceCalculationSignature()'),'Completed estimate records the actual model, search and assigned unit')
        r.evaluate('showTab(4)');r.locator('#variogramModelCustom>summary').click();r.locator('#varRange').fill('888');r.locator('button[onclick="updateModel()"]').click()
        r.locator('#tab4 [data-workflow-next]').click()
        check(r.evaluate('!estimState.done && !estimState.results && !crossvalState.metrics'),'Applied custom model changes invalidate prior estimates and cross-validation')
        r.locator('#tab5 [data-workflow-next]').click();r.locator('#tab6 [data-workflow-next]').click()
        r.wait_for_function('()=>document.getElementById("tab7").classList.contains("active")',timeout=120000)
        check(r.evaluate('estimState.appliedSignature===resourceCalculationSignature()') and r.evaluate('estimState.appliedSignature')!=applied,'Guided continuation recomputes using the changed custom model')
        r.locator('#tab7 [data-workflow-next]').click();r.wait_for_function('()=>document.getElementById("tab10").classList.contains("active")',timeout=120000)
        r.locator('#tab10 [data-workflow-next]').click()
        check(r.locator('#tab12').evaluate('e=>e.classList.contains("active")') and r.locator('#pdf-export-btn').is_visible(),'Primary workflow reaches the real Resource report and native PDF action')
        check(r.evaluate('renderFailures.length===0'),'Automatic uploaded workflow has no swallowed renderer failures')
        r.close()
        r=open_page(b,'Resource')
        # Known regular grid: adjacent 10×20×5 cells. Internal face must be culled (20 triangles, not 24).
        mesh=r.evaluate("_blockMeshTrace([100,110],[200,200],[300,300],[0,1],10,20,5,{colorscale:'Viridis'},true,['left','right'])")
        check(len(mesh['i'])==20,'Two adjacent cells render their ten exterior faces without an internal wall')
        check(min(mesh['x'])==95 and max(mesh['x'])==115 and min(mesh['y'])==190 and max(mesh['y'])==210 and min(mesh['z'])==297.5 and max(mesh['z'])==302.5,'Block vertices use exact cell dimensions and absolute coordinates')
        check(set(mesh['text'])=={'left','right'},'Block hover retains source inspection text')
        whole=r.evaluate("""() => {const x=[],y=[],z=[],v=[];for(let i=0;i<3;i++)for(let j=0;j<3;j++)for(let k=0;k<3;k++){x.push(i*10);y.push(j*10);z.push(k*10);v.push(1)}return _blockMeshTrace(x,y,z,v,10,10,10,{colorscale:'Viridis'},true)}""")
        check(len(whole['i'])==108,'3×3×3 grid has exactly 54 external faces, including complete interior-cell culling')
        # Known-answer estimated fixture isolates rendering from expensive estimation; values must stay unchanged.
        r.evaluate("""() => {blockState.blocks=Array.from({length:2100},(_,i)=>({cx:(i%30)*10,cy:(Math.floor(i/30)%10)*10,cz:Math.floor(i/300)*5}));blockState.size=[10,10,5];estimState.results={ok:Array.from({length:2100},(_,i)=>i%5),idw:Array(2100).fill(1),nn:Array(2100).fill(1),variance:Array(2100).fill(2),nNb:Array(2100).fill(6),estimated:2100};estimState.done=true;classState.labels=null;window.webglAvailable=()=>true;window._plots=[];window._realNewPlot=Plotly.newPlot;Plotly.newPlot=function(id,data,layout){if(id==='d3Plot'){_plots.push({data,layout});document.getElementById(id).textContent='known-geometry-render';return Promise.resolve()}return _realNewPlot.apply(this,arguments)};showTab(6)}""")
        values=r.evaluate('JSON.stringify([blockState.blocks,estimState.results])')
        r.locator('#tab6 [data-related-stage="11"]').click()
        check(r.locator('#orebitCrumb').inner_text()==r.locator('nav.tabs .tab').nth(10).inner_text().strip(),'Resource header follows direct 3D inspection')
        check(r.locator('#d3Rep').input_value()=='surface','Estimated geometry starts as a connected full-grid surface')
        check(r.evaluate('_plots.at(-1).data[0].type==="mesh3d" && Math.max(..._plots.at(-1).data[0].x)===295'),'Default surface includes outermost cells even beyond 2000 display limit')
        check('All filtered cells represented' in r.locator('#d3PlotNote').inner_text(),'Viewer explicitly discloses full filtered surface and cell dimensions')
        r.locator('#threeDContent details>summary').click()
        r.locator('#d3Cut').fill('3');r.locator('#d3Cut').press('Tab')
        check(values==r.evaluate('JSON.stringify([blockState.blocks,estimState.results])'),'Display cutoff never changes estimate values or block population')
        r.locator('#d3Max').fill('3');r.locator('#d3Max').press('Tab')
        check(r.evaluate('_filteredBlockIndexes().length===420 && _filteredBlockIndexes().every(i=>estimState.results.ok[i]===3)'), 'Inclusive equal bounds show exactly the requested grade, without rejecting zero-width ranges')
        r.locator('#d3Cut').fill('2');r.locator('#d3Cut').press('Tab')
        r.locator('#d3Scale').select_option('custom');r.locator('#d3Breaks').fill('2, 3');r.locator('#d3Breaks').press('Tab')
        r.locator('#d3Palette').select_option('viridis')
        check(r.evaluate('_filteredBlockIndexes().length===840'), 'Grade range includes both endpoints and excludes all other blocks')
        check(r.evaluate("_plots.at(-1).data[0].colorbar.ticktext.join('|')===blockSectionPlot.data[0].marker.colorbar.ticktext.join('|')"), 'Custom class boundaries and units are identical in 3D and real 2D Plotly legends')
        check(r.evaluate("JSON.stringify(_plots.at(-1).data[0].colorscale)===JSON.stringify(blockSectionPlot.data[0].marker.colorscale)"), 'Selected Viridis palette is shared by mesh and 2D view')
        count=r.evaluate('_plots.length');r.locator('#d3Max').fill('1');r.locator('#d3Max').press('Tab')
        check(r.locator('#d3Validation').is_visible() and r.evaluate('_plots.length')==count, 'Reversed range explains the error and retains the last valid plot')
        r.locator('#d3Max').fill('3');r.locator('#d3Max').press('Tab');count=r.evaluate('_plots.length')
        r.locator('#d3Breaks').fill('3, 2');r.locator('#d3Breaks').press('Tab')
        check(r.locator('#d3Validation').is_visible() and r.evaluate('_plots.length')==count, 'Non-increasing custom boundaries never produce a misleading legend')
        r.locator('#d3Scale').select_option('linear')
        check(r.evaluate('blockSectionPlot.data[0].marker.cmin===2 && blockSectionPlot.data[0].marker.cmax===3'), 'Linear scale displays the absolute full-range grade bounds')
        r.evaluate('webglAvailable=()=>false;render3DPlot()')
        check(r.evaluate('fbPlan.data[0].marker.cmin===2 && fbPlan.data[0].marker.cmax===3 && fbPlan.data[0].x.length===840'), 'No-WebGL fallback keeps the same range, scale and full-population limits')
        r.locator('#d3Cut').fill('');r.locator('#d3Cut').press('Tab');r.locator('#d3Max').fill('0');r.locator('#d3Max').press('Tab')
        check(r.evaluate('_filteredBlockIndexes().length===420 && _filteredBlockIndexes().every(i=>estimState.results.ok[i]===0)'), 'Blank lower bound and an upper bound of zero preserve genuine zero grades')
        r.locator('#d3Max').fill('-1');r.locator('#d3Max').press('Tab')
        check(r.locator('#d3Validation').is_visible() and r.evaluate('_filteredBlockIndexes().length===0'), 'A valid empty range shows an explicit no-block result without retaining a misleading model')
        check(values==r.evaluate('JSON.stringify([blockState.blocks,estimState.results])'), 'Ranges, palettes, invalid edits and fallback never mutate blocks or numerical estimates')
        r.locator('#d3Cut').fill('3');r.locator('#d3Cut').press('Tab');r.locator('#d3Max').fill('');r.locator('#d3Max').press('Tab')
        r.evaluate('showTab(6);showTab(11)')
        check(r.locator('#d3Cut').input_value()=='3','View filters survive leaving and reopening the viewer')
        for language in ('id','en'):
            r.evaluate('(language)=>{applyLanguage(language);showTab(6)}',language)
            check('flow.' not in r.locator('#tab6 .workflow-related').inner_text(),'Related checks are localized in '+language)
        for width in (390,320):
            r.set_viewport_size({'width':width,'height':844});r.evaluate('showTab(11)')
            check(r.locator('#d3Cut').is_visible() and r.locator('#d3Max').is_visible(), 'Grade range remains directly accessible on mobile')
            check(r.evaluate('document.documentElement.scrollWidth<=innerWidth+2'),'Related tools fit '+str(width)+' px without horizontal overflow')
        check(r.evaluate('renderFailures.length===0'),'Resource related navigation has no swallowed render failures: '+str(r.evaluate('renderFailures')))
        r.evaluate("window._blockViewSettings={d3Cut:'99'};resetToSample()")
        check(r.evaluate('window._blockViewSettings===null'),'A new dataset clears old viewer filters so a commodity is not silently hidden')
        r.close();b.close()
finally:server.shutdown();server.server_close()
print('SCREENING CONTEXT:',passed,'passed',flush=True)
