#!/usr/bin/env python3
"""Generate the PyInstaller --version-file resources from the version SSOT.

WHY THIS EXISTS
    version_info_{core,assay,resource}.txt used to be hand-maintained. Nothing
    checked them: version-sync-guard.sh does not know about them, so they sat at
    2.7.1 while geosuite-changelog.json said v2.7.8, and the v2.7.8 build came
    out stamped 2.7.1 in its Windows version resource. The runbook already
    warned this exact failure had happened once before and cost a full
    rebuild + re-sign cycle; it happened again because the files were a copy of
    the version rather than a projection of it.

    Generating them at build time removes the copy. build_exe.py calls this
    before building, so the stamp cannot disagree with the SSOT again.

VERSION SOURCE
    orebit-ops:  ops/scripts/orebit/geosuite-changelog.json "current"
    public repo: package.json "version" (kept equal to the changelog by
                 version-sync-guard.sh, and to the release tag by the release
                 workflow)

USAGE
    python gen_version_info.py [--out DIR]           # write the three files
    python gen_version_info.py [--out DIR] --check   # verify only
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CHANGELOG = (
    HERE.parent.parent / "ops" / "scripts" / "orebit" / "geosuite-changelog.json"
)
PACKAGE_JSON = HERE.parent / "package.json"

PRODUCTS = {
    "core": ("Orebit-Core", "Orebit GeoSuite Core - Geological Data Management"),
    "assay": ("Orebit-Assay", "Orebit GeoSuite Assay - Geochemical Analysis"),
    "resource": ("Orebit-Resource", "Orebit GeoSuite Resource - Resource Estimation"),
}

TEMPLATE = """# UTF-8
#
# Version info for {desc}
# Reduces AV false positives: gives the PE file proper company/product metadata.
#
# GENERATED by gen_version_info.py from {src}.
# Do not hand-edit: bump the version and rebuild instead.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, 0),
    prodvers=({a}, {b}, {c}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Orebit'),
         StringStruct('FileDescription', '{desc}'),
         StringStruct('FileVersion', '{ver}'),
         StringStruct('InternalName', '{exe}'),
         StringStruct('LegalCopyright', 'Copyright (c) 2026 Orebit. Licensed under GPL-3.0.'),
         StringStruct('OriginalFilename', '{exe}.exe'),
         StringStruct('ProductName', 'Orebit GeoSuite'),
         StringStruct('ProductVersion', '{ver}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version() -> tuple[str, str]:
    if CHANGELOG.is_file():
        data = json.loads(CHANGELOG.read_text(encoding="utf-8"))
        return data["current"].lstrip("v"), "geosuite-changelog.json"
    if PACKAGE_JSON.is_file():
        data = json.loads(PACKAGE_JSON.read_text(encoding="utf-8"))
        return data["version"].lstrip("v"), "package.json"
    sys.exit(f"ERROR: no version source ({CHANGELOG} or {PACKAGE_JSON})")


def main() -> int:
    check = "--check" in sys.argv
    out = HERE
    if "--out" in sys.argv:
        out = Path(sys.argv[sys.argv.index("--out") + 1])
        out.mkdir(parents=True, exist_ok=True)
    ver, src = read_version()
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", ver)
    if not m:
        print(f"ERROR: SSOT version {ver!r} is not X.Y.Z")
        return 1
    a, b, c = m.groups()

    drift = 0
    for key, (exe, desc) in PRODUCTS.items():
        path = out / f"version_info_{key}.txt"
        want = TEMPLATE.format(a=a, b=b, c=c, ver=ver, exe=exe, desc=desc, src=src)
        if check:
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                cur = re.search(r"'FileVersion', '([^']+)'", have)
                print(
                    f"  DRIFT {path.name}: has {cur.group(1) if cur else '?'}, "
                    f"SSOT says {ver}"
                )
                drift += 1
            else:
                print(f"  OK    {path.name}: {ver}")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  wrote {path.name}  v{ver}")

    if check and drift:
        print(
            f"\n{drift} version-info file(s) disagree with the SSOT — "
            f"run: python gen_version_info.py"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
